### ISSUE TITLE
git-pulls lists error

### ISSUE THREAD

**Issue by tettoffensive** [schacon/git-pulls#65]
Maybe something changed with their API? I'm not getting anything listed and getting this error.

```
$ git-pulls list
Updating mycompany/MyProject
Checking for forks in need of fetching
/Library/Ruby/Gems/2.0.0/gems/git-pulls-0.4.14/lib/git-pulls.rb:229:in `fetch_stale_forks': undefined method `each' for false:FalseClass (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/git-pulls-0.4.14/lib/git-pulls.rb:220:in `update'
    from /Library/Ruby/Gems/2.0.0/gems/git-pulls-0.4.14/lib/git-pulls.rb:32:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/git-pulls-0.4.14/lib/git-pulls.rb:21:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/git-pulls-0.4.14/bin/git-pulls:6:in `<top (required)>'
    from /usr/local/bin/git-pulls:23:in `load'
    from /usr/local/bin/git-pulls:23:in `<main>'
```

**Comment by teekenl** [comment]
make sure you have the gem 'git pulls' installed.

The correct command should => git pull list with dash in between

Have fun in coding.
