### ISSUE TITLE
Tries to talk to public GitHub even when project is on GitHub Enterprise

### ISSUE THREAD

**Issue by hakanai** [schacon/git-pulls#66]
Trying to list pull requests on a repository cloned from GitHub Enterprise generates a 404 because it is making the request from the public `github.com`.

I haven't the foggiest idea which host is supposed to be used when GitHub Enterprise is being used, though.

    $ git-pulls list
    Updating acme/core
    /Users/tester/DevEnv/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/octokit-2.7.2/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/acme/core/pulls?state=open: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)
	from /Users/tester/DevEnv/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
	from /Users/tester/DevEnv/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /Users/tester/DevEnv/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
	from /Users/tester/DevEnv/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/tester/DevEnv/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/tester/DevEnv/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /Users/tester/DevEnv/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sawyer-0.5.5/lib/sawyer/agent.rb:94:in `call'
	from /Users/tester/DevEnv/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/octokit-2.7.2/lib/octokit/client.rb:257:in `request'
	from /Users/tester/DevEnv/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/octokit-2.7.2/lib/octokit/client.rb:194:in `paginate'
	from /Users/tester/DevEnv/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/octokit-2.7.2/lib/octokit/client/pull_requests.rb:20:in `pull_requests'
	from /Users/tester/DevEnv/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/octokit-2.7.2/lib/octokit.rb:27:in `method_missing'
	from /Users/tester/DevEnv/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/git-pulls-0.4.14/lib/git-pulls.rb:346:in `cache_pull_info'
	from /Users/tester/DevEnv/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/git-pulls-0.4.14/lib/git-pulls.rb:219:in `update'
	from /Users/tester/DevEnv/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/git-pulls-0.4.14/lib/git-pulls.rb:32:in `run'
	from /Users/tester/DevEnv/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/git-pulls-0.4.14/lib/git-pulls.rb:21:in `start'
	from /Users/tester/DevEnv/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/git-pulls-0.4.14/bin/git-pulls:6:in `<top (required)>'
	from /Users/tester/DevEnv/rbenv/versions/2.4.0/bin/git-pulls:22:in `load'
	from /Users/tester/DevEnv/rbenv/versions/2.4.0/bin/git-pulls:22:in `<main>'

**Comment by davrsky** [comment]
the readme tells you what to do in this case
